### ISSUE TITLE
Add ParticipantNotificationMessage for consistency in Messages

### ISSUE THREAD

**Issue by HaydarAk** [IndustrialDataSpace/InformationModel#102]
Participant related NotificiationMessages (in the Messages.ttl taxonomy) do not have a proper superclass like the **ConnectorNotificationMessage** and **ResourceNotificationMessage**.
Add class for consistency.

- [ ] Add ParticipantNotificationMessage as superclass to all Participant_____Messages 
- [ ] Make ParticipantNotificationMessage subclass of NotificationMessage

**Comment by Madmatti** [comment]
I am rather confused. The current state of the code shows:

```
ids:ParticipantNotificationMessage a owl:Class;
    rdfs:subClassOf ids:NotificationMessage ;
[...]

ids:ParticipantAvailableMessage a owl:Class;
    rdfs:subClassOf ids:ParticipantNotificationMessage ;
[...]
```

So "NotificationMessage" is superclass of the "ParticipantNotificationMessage", which is in turn superclass of all "Participant______Messages". 

I don't see any changes to this code section since you created this issue. Am I missing something?

**Comment by HaydarAk** [comment]
Oh sorry, you're right. 
Maybe I have looked at a (local) old version of the information model, instead of the version in the repository...
