### ISSUE TITLE
Access URL is a URI

### ISSUE THREAD

**Issue by maboeckmann** [IndustrialDataSpace/InformationModel#146]
Very minor thing I just noticed:
https://github.com/IndustrialDataSpace/InformationModel/blob/develop/model/communication/Host.ttl#L39

The property AccessURL has range xsd:anyURI. Should we rename the property to AccessURI or change the range to xsd:anyURL?

**Comment by HaydarAk** [comment]
As far as I know, there is no xsd:anyUR**L**.  We are using xsd:anyURI because it is the 
closest to an URL. 

 I'd suggest to leave it like this. The name / label fits but the  datatype allows more than just URLs. 
The inconsistency comes from the missing _xsd:_ property for UR**L**s.  But, we are expecting any kind of http / mqtt / ... URL.

**Comment by maboeckmann** [comment]
Ah you are right. They don't have an any url...
