### ISSUE TITLE
Version identifier for message payload

### ISSUE THREAD

**Issue by cmader** [IndustrialDataSpace/InformationModel#66]
In the message header, we need a way to specify an optional version identifier of the payload information. That version identifier should indicate the version of the *description* of the information in the payload.
The reationale is that we need some way to refer to information that was once sent to some other system on the ids (e.g., a broker) but which is now out of date and needs to be updated. This is especially needed if, e.g., a connector wants to update its self description on a broker via a patch ("diff") document, both the connector and the broker need to refer to the same version of the existing description in order to create and to apply the patch.
A connector config update message therefore needs to refer to (i) the old version identifier and (ii) the version that the information should have after successful application of the patch.

**Comment by jpullmann** [comment]
Hi Christian, adding payload version is a definitely a valid extension. I am not sure about its relation to the metadata and would suggest to distinguish the version of content (resource/artifact/payload) as opposed to version of its description, since both may evolve independently. Similarly DCAT distinguishes the [Catalog record](https://www.w3.org/TR/vocab-dcat-2/#Property:record_update_date) version from [Resource](https://www.w3.org/TR/vocab-dcat-2/#Property:resource_update_date) version. This is esp. interesting,  when contractual terms have changed while the content remains the same.

**Comment by sebbader** [comment]
prepared and soon to be merged

**Comment by HaydarAk** [comment]
Added in a5be2c342464aa8677895bc823180140073dab1c
